os: linux
dist: xenial
language: shell

env:
  global:
    - PERIBOLOS_TAG=v20200826-f9138eb980

stages:
  - name: validate-email
    if: branch = master AND type = pull_request # only on PRs to master
  - name: peribolos
    if: branch = master AND type IN (push, cron)

jobs:
  include:
    - stage: validate-email
      script:
        - AUTHOR_EMAIL=$(git log -1 "origin/${TRAVIS_PULL_REQUEST_BRANCH}" --pretty="%aE")
        - if [[ ! $AUTHOR_EMAIL =~ ^[a-z.]+@baloise\.[a-z]{2,3}$ ]]; then echo "Commit author (${AUTHOR_EMAIL}) doesn't have a '@baloise.TLD' email address!"; exit 1; fi
    - stage: peribolos
      services: docker
      script:
        - echo $TOKEN > /tmp/TOKEN
        - docker run --rm
            -v /tmp/TOKEN:/etc/github/oauth
            -v $(pwd)/config.yaml:/etc/config/config.yaml
            gcr.io/k8s-prow/peribolos:$PERIBOLOS_TAG
            --github-token-path /etc/github/oauth
            --config-path /etc/config/config.yaml
            --fix-org
            --fix-org-members
            --fix-team-members
            --fix-teams
            --fix-team-repos
            --confirm
