orgs:
  baloise-incubator:
    name: Baloise Group - Incubator
    billing_email: Group.CH_Open-Source@baloise.ch
    company: ""
    default_repository_permission: write
    description: Evaluation and incubation of new technologies for the Baloise Group
    email: Group.CH_Open-Source@baloise.ch
    has_organization_projects: true
    has_repository_projects: true
    location: Aeschengraben 21, 4002 Basel, Switzerland
    members_can_create_repositories: true
    admins:
    - baopso
    - culmat
    - hirsch88
    - incubator-tekton
    - joachimprinzbach
    - niiku
    - patrit
    - arburk
    - koenigle
    - kullmanp 
    - Tiliavir
    - svene
    - robert-groensfeld
    - danielgrob
    - d038496
    - dweber019
    - jonasz-lasut-baloise
    members:
    - ArivinK
    - jembas
    - Alex-Thoma
    - baloise-incubator-bot
    - alexsoeres
    - chris-lipp
    - christiansiegel
    - christophgeering
    - clastzoo
    - clemensgbasler
    - CookieMonster70
    - daniel-st
    - dianaracho
    - Dr-Tech81
    - fabio-tedesco
    - felixkrohn
    - frank-baier
    - Gagne87
    - gerohoff
    - geschba
    - geschbach
    - Ginious
    - GinaBiondo-aperto
    - hannah-mat
    - janineKleessen
    - jacnguymesoneer
    - JohnnyGoodNews
    - jordilaforge
    - JasperDeLanghe
    - l0r5
    - leubedane
    - luechtdiode
    - MarkusFlorian79
    - max-voss
    - mbobzin
    - mladenplaninicic
    - miksaylo87
    - niels-oz
    - nobilo
    - NoraKurzbein
    - rainerblumenthal
    - sbubendorf
    - schlijo
    - soenkeSchmidt
    - serialcool
    - StephanSST
    - stefanbukovski
    - m4rc0z
    - Resurrectum
    - tbe1
    - tirun
    - tklueber
    - trichie
    - ThomasSeyssensTPO
    - vangual
    - yannickholzenkamp
    - mikevader
    - mkasparsone
    - ArthurNeudeck
    - mateuszbaloise
    - skytime-sh
    - lbiry
    - whvneo
    - hammsu01
    - RotscherK
    - sobabufe
    - Mission71
    - MelPiw
    - lagoaresti
    - sebastianzillessen
    - stefanschoe
    - janbrohl
    - antoninoprovenzanobaloise
    - AlainLatscha
    - renat1sakenov
    - gitops-demo-user
    - kamrwo
    - mebagel
    - madaluca
    - sebaotlacan
    - Sw0rdiX
    - th-basler
    - pkreisel
    - dombosfi
    - mikeleber
    - gueltekinB
    - harry08
    - l-brendle
    - janhkrueger
    - RiLi2001
    - volkerbasler
    - viclientali
    - frevers81
    - monkold
    - henriks23
    - nataliia-karpenko
    - tommuelli
    - makrelas
    - marcschmidlin
    - ingenuity2k
    - nteofilovic
    - koljaju
    - FilipMarkovski
    - hejransa
    - lazaki
    - predrag-arsic
    - Schneidarr
    - trikke-basel    
    - daniel-battaglia
    - m1markus
    - JanMoritz23
    - nikolakib
    - Dchamp1
    - nghia9691
    - balsst
    - mariusbaloise
    - smngld
    - SarajAtBaloise
    - girafi
    - MartinBartolome
    - tschei65
    - das-ist-bitter
    teams:
      Organization Managers:
        description: Baloise Incubator GitHub Organization Managers
        maintainers:
        - baopso
        members:
        - culmat
        - hirsch88
        - incubator-tekton
        - joachimprinzbach
        - niiku
        - patrit
        - arburk
        - kullmanp 
        - Tiliavir
        - svene
        - danielgrob
        - d038496
        - dweber019
        privacy: closed
        repos:
          org: admin
      cc2023_diabetes:
        description: Codecamp 2023 Team Diabetes
        maintainers:
        - svene
        members:
        - m4rc0z
        - JanMoritz23
        privacy: closed
        repos:
          cc2023_diabetes_springboot: admin
