orgs:
  baloise-incubator:
    admins:
    - baopso
    - culmat
    - hirsch88
    - incubator-tekton
    - joachimprinzbach
    - MarkusTiede
    - niiku
    - patrit
    - marcschmidlin
    billing_email: Group.CH_Open-Source@baloise.ch
    company: ""
    default_repository_permission: write
    description: Evaluation and incubation of new technologies for the Baloise Group
    email: Group.CH_Open-Source@baloise.ch
    has_organization_projects: true
    has_repository_projects: true
    location: Aeschengraben 21, 4002 Basel, Switzerland
    members:
    - ArivinK
    - jembas
    - Alex-Thoma
    - arburk
    - baloise-incubator-bot
    - alexsoeres
    - chris-lipp
    - christiansiegel
    - christophgeering
    - clastzoo
    - clemensgbasler
    - CookieMonster70
    - daniel-st
    - danielgrob
    - dianaracho
    - Dr-Tech81
    - fabio-tedesco
    - felixkrohn
    - frank-baier
    - Gagne87
    - gerohoff
    - geschba
    - geschbach
    - Ginious
    - GinaBiondo-aperto
    - janineKleessen
    - jacnguymesoneer
    - JohnnyGoodNews
    - jordilaforge
    - JasperDeLanghe
    - kullmanp 
    - l0r5
    - leubedane
    - luechtdiode
    - MarkusFlorian79
    - max-voss
    - mbobzin
    - mladenplaninicic
    - miksaylo87
    - niels-oz
    - nobilo
    - NoraKurzbein
    - rainerblumenthal
    - sbubendorf
    - schlijo
    - soenkeSchmidt
    - serialcool
    - StephanSST
    - stefanbukovski
    - svene
    - m4rc0z
    - tbe1
    - tirun
    - tklueber
    - trichie
    - ThomasSeyssensTPO
    - vangual
    - yannickholzenkamp
    - mikevader
    - mkasparsone
    - ArthurNeudeck
    - mateuszbaloise
    - skytime-sh
    - lbiry
    - whvneo
    - hammsu01
    - RotscherK
    - sobabufe
    - Mission71
    - MelPiw
    - lagoaresti
    - sebastianzillessen
    - stefanschoe
    - janbrohl
    - antoninoprovenzanobaloise
    - AlainLatscha
    - renat1sakenov
    - gitops-demo-user
    - MarcoUebner
    - kamrwo
    - mebagel
    - madaluca
    - sebaotlacan
    - th-basler
    - MartinV-DevOps
    - pkreisel
    - dombosfi
    - mikeleber
    - gueltekinB
    - dweber019
    - harry08
    - l-brendle
    - d038496
    - janhkrueger
    - RiLi2001
    - rainerblumentha√∂
    - volkerbasler
    - viclientali
    - koenigle
    - monkold
    - henriks23
    - Tiliavir
    - czimmermann1
    - nataliia-karpenko
    - tommuelli
    - makrelas
    members_can_create_repositories: true
    name: Baloise Group - Incubator
    teams:
      Organization Managers:
        description: Baloise Incubator GitHub Organization Managers
        maintainers:
        - baopso
        members:
        - culmat
        - hirsch88
        - joachimprinzbach
        - MarkusTiede
        - niiku
        - patrit
        privacy: closed
        repos:
          org: admin
      Alumni:
        description: Former member of the Baloise Incubator Open Source Group
        maintainers:
        - baopso
        members:
        - christiansiegel
        privacy: closed
      ApertoDevs:
        description: Development team of the website
        maintainers:
        - baopso
        - hirsch88
        members:
        - soenkeSchmidt
        - serialcool
        - max-voss
        - GinaBiondo-aperto
        - fabio-tedesco
        - dianaracho
        - madaluca
        - rainerblumenthal
        - MelPiw
        - sebaotlacan
        - janineKleessen
        - fabio-tedesco
        privacy: closed
        repos:
          design-system: write
